### ISSUE TITLE
Empty user table on first start

### ISSUE THREAD

**Issue by galindocode** [c9845/licensekeys#4]
When I open and start the license web server for the first time I can't find which user to use to login, and when I explore the user table I see that it is empty.

**Comment by c9845** [comment]
This has been fixed in v3.0.2 per commit d6c2305.

Please download v3.0.2, build, delete the previously deployed database, and deploy the database again.  The logging will output the default username and password for the initial user.

This issue popped up in v3.0.0, previous versions are not affected.

Thanks for catching this!
